import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
const defaultOptions = {} as const;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  ISO8601DateTime: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

/** Autogenerated input type of CreateQuery */
export type CreateQueryInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  /** The project ID to create the query for */
  projectId: Scalars['ID']['input'];
  /** The query text to analyze */
  query: Scalars['String']['input'];
};

/** Autogenerated return type of CreateQuery. */
export type CreateQueryPayload = {
  __typename?: 'CreateQueryPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  /** List of errors if the mutation failed */
  errors: Array<Scalars['String']['output']>;
  /** The created query */
  query?: Maybe<QueryModel>;
};

export type Mutation = {
  __typename?: 'Mutation';
  /** Create a new query for AI analysis. API key required unless project is in public published projects list. */
  createQuery?: Maybe<CreateQueryPayload>;
};


export type MutationCreateQueryArgs = {
  input: CreateQueryInput;
};

/** A project for AI analysis */
export type Project = {
  __typename?: 'Project';
  /** When the project was created */
  createdAt: Scalars['ISO8601DateTime']['output'];
  /** Unique identifier for the project */
  id: Scalars['ID']['output'];
  /** Name of the project */
  name: Scalars['String']['output'];
  /** Type of analysis prompt */
  promptType: PromptTypeEnum;
  /** URL-friendly identifier for the project */
  slug: Scalars['String']['output'];
  /** Current status of the project */
  status?: Maybe<ProjectStatusEnum>;
  /** When the project was last updated */
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** Status of a project */
export enum ProjectStatusEnum {
  /** Project is archived */
  Archived = 'ARCHIVED',
  /** Project is in draft */
  Draft = 'DRAFT',
  /** Project is published */
  Published = 'PUBLISHED'
}

/** Type of prompt for analysis */
export enum PromptTypeEnum {
  /** AI detection analysis */
  IsItAi = 'IS_IT_AI',
  /** Spam detection analysis */
  IsItSpam = 'IS_IT_SPAM',
  /** Sentiment analysis */
  Sentiment = 'SENTIMENT',
  /** Topic extraction analysis */
  Topics = 'TOPICS'
}

export type Query = {
  __typename?: 'Query';
  /** Find a project by ID or slug */
  project?: Maybe<Project>;
  /** List all projects */
  projects: Array<Project>;
  /** Public list of published projects for the first user (no owner information) */
  publicPublishedProjects: Array<Project>;
};


export type QueryProjectArgs = {
  id?: InputMaybe<Scalars['ID']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectsArgs = {
  userId?: InputMaybe<Scalars['ID']['input']>;
};

/** A query for AI analysis */
export type QueryModel = {
  __typename?: 'QueryModel';
  /** List of extracted answer terms */
  answer?: Maybe<Array<Scalars['String']['output']>>;
  /** When the query was created */
  createdAt: Scalars['ISO8601DateTime']['output'];
  /** Unique identifier for the query */
  id: Scalars['ID']['output'];
  /** The project this query belongs to */
  projectId: Scalars['ID']['output'];
  /** The query text to analyze */
  query: Scalars['String']['output'];
  /** The AI analysis response */
  response?: Maybe<Scalars['JSON']['output']>;
  /** When the query was last updated */
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type GetPublicPublishedProjectsQueryVariables = Exact<{ [key: string]: never; }>;


export type GetPublicPublishedProjectsQuery = { __typename?: 'Query', publicPublishedProjects: Array<{ __typename?: 'Project', id: string, name: string, slug: string, status?: ProjectStatusEnum | null, promptType: PromptTypeEnum, createdAt: any, updatedAt: any }> };

export type CreateQueryMutationVariables = Exact<{
  input: CreateQueryInput;
}>;


export type CreateQueryMutation = { __typename?: 'Mutation', createQuery?: { __typename?: 'CreateQueryPayload', errors: Array<string>, query?: { __typename?: 'QueryModel', id: string, query: string, response?: any | null, answer?: Array<string> | null, projectId: string, createdAt: any } | null } | null };


export const GetPublicPublishedProjectsDocument = gql`
    query GetPublicPublishedProjects {
  publicPublishedProjects {
    id
    name
    slug
    status
    promptType
    createdAt
    updatedAt
  }
}
    `;

/**
 * __useGetPublicPublishedProjectsQuery__
 *
 * To run a query within a React component, call `useGetPublicPublishedProjectsQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetPublicPublishedProjectsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetPublicPublishedProjectsQuery({
 *   variables: {
 *   },
 * });
 */
export function useGetPublicPublishedProjectsQuery(baseOptions?: Apollo.QueryHookOptions<GetPublicPublishedProjectsQuery, GetPublicPublishedProjectsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<GetPublicPublishedProjectsQuery, GetPublicPublishedProjectsQueryVariables>(GetPublicPublishedProjectsDocument, options);
      }
export function useGetPublicPublishedProjectsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GetPublicPublishedProjectsQuery, GetPublicPublishedProjectsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<GetPublicPublishedProjectsQuery, GetPublicPublishedProjectsQueryVariables>(GetPublicPublishedProjectsDocument, options);
        }
// @ts-ignore
export function useGetPublicPublishedProjectsSuspenseQuery(baseOptions?: Apollo.SuspenseQueryHookOptions<GetPublicPublishedProjectsQuery, GetPublicPublishedProjectsQueryVariables>): Apollo.UseSuspenseQueryResult<GetPublicPublishedProjectsQuery, GetPublicPublishedProjectsQueryVariables>;
export function useGetPublicPublishedProjectsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<GetPublicPublishedProjectsQuery, GetPublicPublishedProjectsQueryVariables>): Apollo.UseSuspenseQueryResult<GetPublicPublishedProjectsQuery | undefined, GetPublicPublishedProjectsQueryVariables>;
export function useGetPublicPublishedProjectsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<GetPublicPublishedProjectsQuery, GetPublicPublishedProjectsQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<GetPublicPublishedProjectsQuery, GetPublicPublishedProjectsQueryVariables>(GetPublicPublishedProjectsDocument, options);
        }
export type GetPublicPublishedProjectsQueryHookResult = ReturnType<typeof useGetPublicPublishedProjectsQuery>;
export type GetPublicPublishedProjectsLazyQueryHookResult = ReturnType<typeof useGetPublicPublishedProjectsLazyQuery>;
export type GetPublicPublishedProjectsSuspenseQueryHookResult = ReturnType<typeof useGetPublicPublishedProjectsSuspenseQuery>;
export type GetPublicPublishedProjectsQueryResult = Apollo.QueryResult<GetPublicPublishedProjectsQuery, GetPublicPublishedProjectsQueryVariables>;
export const CreateQueryDocument = gql`
    mutation CreateQuery($input: CreateQueryInput!) {
  createQuery(input: $input) {
    query {
      id
      query
      response
      answer
      projectId
      createdAt
    }
    errors
  }
}
    `;
export type CreateQueryMutationFn = Apollo.MutationFunction<CreateQueryMutation, CreateQueryMutationVariables>;

/**
 * __useCreateQueryMutation__
 *
 * To run a mutation, you first call `useCreateQueryMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateQueryMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createQueryMutation, { data, loading, error }] = useCreateQueryMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useCreateQueryMutation(baseOptions?: Apollo.MutationHookOptions<CreateQueryMutation, CreateQueryMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CreateQueryMutation, CreateQueryMutationVariables>(CreateQueryDocument, options);
      }
export type CreateQueryMutationHookResult = ReturnType<typeof useCreateQueryMutation>;
export type CreateQueryMutationResult = Apollo.MutationResult<CreateQueryMutation>;
export type CreateQueryMutationOptions = Apollo.BaseMutationOptions<CreateQueryMutation, CreateQueryMutationVariables>;